stages:
  - dependencies-core
  - dependencies-io
  - build

before_script:
  - yum -y install cmake glibc-devel which
  - set +e && source CI/setup_lcg.sh; set -e

variables:
  CMAKE_BASE_ARGS: -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
  GIT_SUBMODULE_STRATEGY: recursive

geomodelcore-build:
  stage: dependencies-core
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelCore.git
    - mkdir geomodelcore-build
    - cd geomodelcore-build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelCore
    - make -j$(nproc)
    - make install
  artifacts: 
    paths:
      - install

geomodelio-build:
  stage: dependencies-io
  script:
    - pwd; ls
    - git clone https://gitlab.cern.ch/GeoModelDev/GeoModelIO.git
    - mkdir geomodelio-build
    - cd geomodelio-build
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../GeoModelIO
    - make -j$(nproc)
    - make install
  artifacts: 
    paths:
      - install
    
    
    
.build_template: &build_template
  stage: build
  tags: 
    - cvmfs
  script:
    - echo "PWD; LS"
    - pwd; ls
    - mkdir build
    - cd build
    - echo "${CMAKE_ARGS}"
    - cmake ${CMAKE_ARGS}  ..
    - cmake --build . -- -j$(nproc)
    #- cmake --build . -- install #TODO: re-enable when 'install' will be set in sub-packages

# build_slc6:
#   <<: *build_template
#   image: cern/slc6-base
#   variables:
#     CMAKE_ARGS: ${CMAKE_BASE_ARGS}

build_cc7:
  <<: *build_template
  image: cern/cc7-base
  variables:
    CMAKE_ARGS: ${CMAKE_BASE_ARGS}
